enterprise-beans/_index.md, messaging/_index.md
This lays some groundwork for a proper landing page that lists each specification with a summary.
I will couple this with an update to the jakarta.ee website that results in rendering along these lines:
The implication being that we'll need an _index.md in the root of each specification directory that contains only metadata that describes the specification for the purposes of rendering this list. As I indicate in the commit message, these files are not version-specific and so will not change frequently (if ever).
=> Add index pages for each specification.

annotations/1.3/_index.md, dependency-injection/1.0/_index.md, mail/1.6/_index.md
This commit adds ballot results and fixes minor issues with the specification documents for:
* Jakarta Mail
* Jakarta Annotations
* Jakarta Dependency Injection
=> Add ballot results and minor formatting fixes

annotations/1.3/_index.md, concurrency/1.1/_index.md, dependency-injection/1.0/_index.md, mail/1.6/_index.md, messaging/2.0/_index.md
Signed-off-by: Wayne Beaton <wayne.beaton@eclipse-foundation.org>
I've broken with best practices, and have included some small tweaks to the other specification documents with this.
=> Add ballot results for concurrency and messaging.

deployment/1.7/_index.md
This commit updates the date and ballot results for the Jakarta Deployment descriptor file.
=> Update Jakarta Deployment descriptor

cdi/2.0/_index.md, cdi/2.0/cdi-spec-2.0.html, cdi/_index.md
When creating a specification project release review, create two PRs with the content divided as follows.
Include the following in PR#1:
a Compatible Implementation and TCK, to ensure that the spec is
implementable and testable.
is complete, passes the TCK, and that the TCK includes sufficient
coverage of the specification. The TCK users guide MUST include
the instructions to run the compatible implementations used to
validate the release.  Instructions MAY be by reference.
http://download.eclipse.org/ee4j/cdi/cdi-tck-2.0.6-dist.zip
https://github.com/eclipse-ee4j/cdi/issues/410
Include the following in PR#2:
=> Jakarta Contexts Dependency Injection 2.0

transactions/_index.md
The top-level Transactions _index.md file was not formatted correctly.
=> fix formatting of _index.md

transactions/_index.md
Not sure how, but I managed to delete it. Let's put it back.
=> Add the transactions index page back.

.gitignore, build.sh, netlify.toml
=> Ability to view previews of each pull request #102

xml-registries/1.0/_index.md, xml-registries/_index.md
=> remove invalid comments

netlify.toml
=> disallow_robots_txt from indexing preview site

deployment/1.7/_index.md
=> Jakarta Deployment links fixed

annotations/1.3/_index.md
=> Fixed Jakarta Annotations TCK link

connectors/1.7/_index.md
=> Fix the connectors TCK link

LICENSE
=> add Eclipse Public License - v 2.0 LICENSE file

interceptors/1.2/_index.md, platform/8/_index.md, webprofile/8/_index.md
Signed-off-by: Bill Shannon <bill.shannon@oracle.com>
=> Update platform TCK links to latest 8.0.1 version.

jsonb/1.0/_index.md
Signed-off-by: Bill Shannon <bill.shannon@oracle.com>
=> Update JSONB TCK to latest 1.0.1 version.

activation/2.0/_index.md, enterprise-beans/4.0/_index.md
This PR adds ballot results for the plan reviews of Jakarta Enterprise Beans 4.0 and Jakarta Activation 2.0.
=> Add ballot results for enterprise-beans 4.0 and activation 2.0

nosql/_index.md
Signed-off-by: otaviopolianasantana@gmail.com
This PR is to add Jakarta NoSQL to the list of specifications.
=> Add Jakarta NoSQL

mvc/_index.md
=> Add short summary description for Jakarta MVC

concurrency/2.0/_index.md
Signed-off-by: Steve Millidge <steve.millidge@payara.fish>
When creating a specification project release review, create two PRs with the content divided as follows.
Include the following in PR#1:
a Compatible Implementation and TCK, to ensure that the spec is
implementable and testable.
is complete, passes the TCK, and that the TCK includes sufficient
coverage of the specification. The TCK users guide MUST include
the instructions to run the compatible implementations used to
validate the release.  Instructions MAY be by reference.
<add URL here>
<add URL here>
<add URL here>
Include the following in PR#2:
=> Jakarta Concurrency 2.0.0-RC2

jsonp/2.0/_index.md
When creating a specification project release review, create two PRs with the content divided as follows.
Include the following in PR#1:
a Compatible Implementation and TCK, to ensure that the spec is
implementable and testable.
is complete, passes the TCK, and that the TCK includes sufficient
coverage of the specification. The TCK users guide MUST include
the instructions to run the compatible implementations used to
validate the release.  Instructions MAY be by reference.
https://repo1.maven.org/maven2/jakarta/json/jakarta.json-api/2.0.0-RC2
http://download.eclipse.org/ee4j/jakartaee-tck/master/nightly/jsonp-tck-2.0.0.zip
<add URL here> …
=> Json Processing 2.0 specification milestone draft

mvc/_index.md
=> Rename variable for 60 char summary to summary60Char

dependency-injection/_index.md
=> Add project id for Dependency Injection

enterprise-ws/_index.md, managedbeans/_index.md, soap-attachments/_index.md, web-services-metadata/_index.md
=> Add missing project ids

debugging/_index.md
=> Add project id for Debugging for lang support

connectors/2.0/_index.md
When creating a specification project release review, create two PRs with the content divided as follows.
Include the following in PR#1:
a Compatible Implementation and TCK, to ensure that the spec is
implementable and testable.
is complete, passes the TCK, and that the TCK includes sufficient
coverage of the specification. The TCK users guide MUST include
the instructions to run the compatible implementations used to
validate the release.  Instructions MAY be by reference.
https://jakarta.oss.sonatype.org/service/local/repo_groups/staging/content/jakarta/resource/jakarta.resource-api/2.0.0-RC2/jakarta.resource-api-2.0.0-RC2.jar
<add URL here>
<add URL here>
Include the following in PR#2:
=> Jakarta Connectors 2.0.0-RC2

authentication/2.0/_index.md
=> Fixing wrong file name in authentication 2.0 draft

pull_request_template.md
Add note about checking and marking items as N/A
=> Changes from today's committee call

batch/2.0/_index.md
Updated _index.md with the ballot results.
=> insert Batch ballot result

batch/2.0/_index.md
=> add Scott Wang vote to Jakarta Batch 2.0 result

authorization/2.0/_index.md
=> Update link to Authorization TCK SHA

activation/2.0/_index.md
=> Update the ballot for Jakarta Activation 2.0

cdi/3.0/_index.md
Put ballot results on CDI 3.0 Spec page.
=> ballot results for cdi 3.0

mail/2.0/_index.md
Task-Url: https://github.com/jakartaee/specifications/pull/247
Signed-off-by: Werner Keil <werner.keil@gmx.net>
=> 247: Jakarta Mail 2.0 ballot results

soap-attachments/2.0/_index.md
Inserting the ballot results for Jakarta SOAP w/ Attachments 2.0.  Also, updated the date: field to make the artifacts available now.
=> insert ballot for soap

jsonp/2.0/_index.md
=> Update ballot results for JSON-P 2.0

jsonb/2.0/_index.md
Inserting the ballot for JSON-B 2.0.
=> insert ballot for jsonb 2.0

servlet/5.0/_index.md
Include both the binding and non-binding votes.  Also updated the publish date to match today's date.
=> ballot results for servlet 5.0

nosql/1.0/_index.md
=> Add ballot results for NoSQL 1.0 plan review

web-services-metadata/3.0/_index.md
=> Ballot results for Jakarta Webservices Metadata 3.0

faces/3.0/_index.md
Ballot results for Jakarta Faces 3.0.
https://github.com/jakartaee/specifications/pull/278
Signed-off-by: Andrew Pielage <pandrex247@hotmail.com>
=> Jakarta Faces 3.0 Ballot Results

mvc/1.1/_index.md
Ballot results for the MVC 1.1 release review.
=> insert ballot results for MVC 1.1 release review

debugging/2.0/_index.md
=> Add release ballot results for JDSOL 2.0

concurrency/2.0/_index.md
=> Add release review ballot results for Concurrency 2.0

authentication/2.0/_index.md
=> Add results for Authentication 2.0 release review ballot

annotations/2.0/_index.md
Insert ballot results for Annotations 2.0.
=> Add Ballot Results for Annotations 2.0

messaging/3.0/_index.md
Update for Messaging 3.0 successful ballot
Signed-off-by: Ed Bratt <ed.bratt@oracle.com>
=> Messaging 3.0 Ballot Results

websocket/2.0/_index.md
Websocket ballot results at conclusion of WebSocket 2.0 Release Review
=> WebSocket 2.0 release review ballot results

pages/3.0/_index.md
Updated _index.md with the ballot results.
=> Pages 3.0 ballot results

connectors/2.0/_index.md, tags/2.0/_index.md
for
268: Jakarta Connectors 2.0
and
277: Jakarta Tags 2.0
Signed-off-by: Werner Keil <werner.keil@gmx.net>
=> updates the specification page with the ballot results.

webprofile/9/_index.md
=> Add ballot results for Jakarta EE Web Profile 9 release review

managedbeans/2.0/_index.md
=> Add the managed bean ballot results

interceptors/2.0/_index.md
=> interceptors 2.0 ballot result

mvc/2.0/_index.md
https://projects.eclipse.org/projects/ee4j.mvc/releases/2.0
=> Plan Review for Jakarta MVC 2.0

mvc/2.0/_index.md
=> MVC 2.0 plan review ballot results

tags/2.0/_index.md
=> Corrected links to Tags TCK

platform/9/_index.md
=> Add Platform 9 ballot results

enterprise-beans/4.0/_index.md
=> Add the final ballot vote

restful-ws/3.0/_index.md
=> Update for the RESTful WebServices 3.0 ballot results

xml-binding/3.0/_index.md
=> Add the Jakarta XML Binding 3.0 ballot results

build.sh, netlify.toml
This PR synchronize the work that we did so far in order to translate Jakarta.ee pages, in particular, the specification section.
This PR will allow contributors to review their specification changes in all supported languages. This is English and Chinese for now.
This also bumps the recommended Hugo version to 0.76.5.
=> Adding chinese translation support to previews

mvc/2.0/_index.md
=> Add the MVC 2.0 ballot results

netlify.toml
This is for fix https://bugs.eclipse.org/bugs/show_bug.cgi?id=570505
Signed-off-by: Yi Liu <yi.liu@eclipse-foundation.org>
=> Update node V in netlify

debugging/_index.md
Fix project link in debugging project.
=> Fix broken link to Debugging project

jsonp/2.0/_index.md
Signed-off-by: Thiago Henrique Hupner <thihup@gmail.com>
/cc @leadpony
=> Add Joy as JSON Processing Compatible Implementation

creation_review_pr_template.md, plan_review_pr_template.md, progress_review_pr_template.md, service_release_pr_template.md
Suggested pull request templates for the various reviews.
=> Add review pr templates

jsonp/2.0/_index.md
=> Option 3: Mark spec used for ratification

servlet/5.0/_index.md
=> Update Servlet 5.0 impl used for ratification according to spec committee decision

persistence/3.1/_index.md
https://projects.eclipse.org/projects/ee4j.jpa/releases/3.1
=> Plan for Jakarta Persistence 3.1

persistence/3.1/_index.md
=> Add ballot results for Persistence 3.1 plan review

restful-ws/3.1/_index.md
=> Add ballot results for RESTful Web Services Plan Review

jsonb/2.1/_index.md, jsonb/3.0/_index.md
Signed-off-by: David Kral <david.k.kral@oracle.com>
https://projects.eclipse.org/projects/ee4j.jsonb/releases/2.1.0
=> Jakarta JSON Binding 2.1 Plan Review

jsonb/2.1/_index.md
=> Add ballot results for Jakarta JSON Binding 2.1 Plan Review

mail/2.1/_index.md
https://projects.eclipse.org/projects/ee4j.mail/releases/2.1
=> Jakarta Mail 2.1 Plan Review

jsonb/1.0/_index.md
Fix the ordering of versions to match the other specs
=> Fix ordering of JSON-B

faces/4.0/_index.md
https://projects.eclipse.org/projects/ee4j.faces/releases/4.0
=> Jakarta Faces 4.0 Plan Review

faces/4.0/_index.md
=> add ballot result

mail/2.1/_index.md
Ballot results for https://github.com/jakartaee/specifications/pull/353
=> Add Jakarta Mail Plan Review Ballot Results

soap-attachments/3.0/_index.md
https://projects.eclipse.org/projects/ee4j.jaxws/releases/3.0-jakarta-soap-attachments
=> Jakarta SOAP with Attachments 3.0 Plan Review

expression-language/5.0/_index.md
=> Jakarta EL 5.0 plan review

mvc/2.1/_index.md
https://projects.eclipse.org/projects/ee4j.mvc/releases/2.1
=> Jakarta MVC 2.1 Plan Review

mvc/2.1/_index.md
=> MVC 2.1 Plan Review Ballot results

websocket/2.1/_index.md
=> Jakarta WebSocket 2.1 Plan Review

expression-language/5.0/_index.md
Ballot results for https://github.com/jakartaee/specifications/pull/363
=> Add Jakarta EL 5.0 Plan Review Ballot Results

coreprofile/10/_index.md, coreprofile/_index.md
=> Jakarta EE Core Profile Creation and Plan Review

build.sh, netlify.toml
=> improve netlify build time

coreprofile/10/_index.md
Ballot results for Creation and Plan Review.
=> Successful ballot results for Creation and Plan Review

concurrency/3.0/_index.md
Signed-off-by: Steve Millidge <steve.millidge@payara.fish>
=> Jakarta Concurrency 3.0 Plan Review

concurrency/3.0/_index.md, soap-attachments/1.4/_index.md, soap-attachments/2.0/_index.md, soap-attachments/3.0/_index.md
Ballot complete. Updating with results.
=> Add Plan Review results for Concurrency 3.0

config/_index.md
=> Jakarta Config creation review

platform/9.1/_index.md, webprofile/9.1/_index.md
=> Add Jakarta EE 9.1 Platform and WebProfile ballot results

messaging/3.1/_index.md
=> Jakarta Messaging 3.1 Plan Review

messaging/3.1/_index.md
=> Add Jakarta Messaging 3.1 ballot results

restful-ws/4.0/_index.md
Signed-off-by: Santiago Pericas-Geertsen santiago.pericasgeertsen@oracle.com
https://projects.eclipse.org/projects/ee4j.jaxrs/releases/4.0.0
=> Jakarta RESTful Web Services 4.0 Plan Review

restful-ws/4.0/_index.md
=> Add ballot results for Jakarta REST 4.0

config/_index.md
=> Update Config metadata with short desc and project id

persistence/2.2/_index.md, persistence/3.0/_index.md
=> Update persistence 2.2+3.0 with impl used for ratification

authorization/2.1/_index.md
Ballot results for Authorization 2.1 Plan Review.
=> plan review ballot

authentication/3.0/_index.md
https://projects.eclipse.org/projects/ee4j.authentication/releases/3.0
=> Jakarta Authentication 3.0 Plan Review

authentication/3.0/_index.md
Signed-off-by: Werner Keil <werner.keil@gmx.net>
=> Ballot results for Jakarta Authentication 3.0 Plan Review

jsonp/2.1/_index.md
https://projects.eclipse.org/projects/ee4j.jsonp/releases/2.1
=> Jakarta JSON Processing 2.1 Plan Review

tags/3.0/_index.md
=> Jakarta Standard Tag Library 3.0 Draft Plan

pages/3.1/_index.md
Signed-off-by: Werner Keil <werner.keil@gmx.net>
=> Ballot results for Jakarta JSP 3.1 Plan Review

servlet/6.0/_index.md
=> Jakarta Servlet 6.0 Plan Review

xml-web-services/4.0/_index.md
https://projects.eclipse.org/projects/ee4j.jaxws/releases/4.0-jakarta-xml-web-services
=> Jakarta XML Web Services 4.0 Plan Review

activation/2.1/_index.md
https://projects.eclipse.org/projects/ee4j.jaf/releases/2.1
=> Jakarta Activation 2.1 Plan Review

security/3.0/_index.md
https://projects.eclipse.org/projects/ee4j.es/releases/3.0
=> Jakarta Security 3.0 Plan Review

connectors/2.1/_index.md
Signed-off-by: Steve Millidge <steve.millidge@payara.fish>
=> Jakarta Connectors 2.1 Plan Review

activation/2.1/_index.md
=> Ballot results for Activation 2.1 plan review

security/3.0/_index.md
=> Ballot results for Security 3.0 Plan review

mail/2.1/_index.md
🤦‍♂️
Signed-off-by: Andrew Pielage <pandrex247@hotmail.com>
=> Fix Formatting of Mail 2.1 Results

xml-binding/4.0/_index.md
Updated conclusion date to 2021-06-07
Signed-off-by: Marcelo Ancelmo <marceloancelmo@gmail.com>
=> Add plan review ballot results for xml binding 4.0

webprofile/10/_index.md
N/A - covered by individual component Specifications
N/A - none
N/A - does not apply to Web Profile TCK
=> release plan pr for ee webprofile 10

platform/10/_index.md
Covered in Release Plan -- Removal of two EJB features from Platform definition
No new optional features in this release, but the Platform spec does identify optional features from past releases.
N/A - does not apply to Platform TCK
=> release plan pr for ee platform 10

platform/10/_index.md, webprofile/10/_index.md
=> Add ballot results for Jakarta EE 10 plan review

jsonb/3.0/_index.md
=> Add ballot results for Jakarta JSON Binding 3.0 Plan Review

rpc/_index.md
=> Proposal for Jakarta RPC

activation/2.1/_index.md
Signed-off-by: Jean-Louis Monteiro [jlmonteiro@tomitribe.com](jlmonteiro@tomitribe.com)
=> Add ballot results to Jakarta Activation 2.1

mail/2.1/_index.md
Pending https://github.com/jakartaee/specifications/pull/428
=> Mail 2.1 Release Results

soap-attachments/3.0/_index.md
Added Review ballot voting details.
=> SOAP-Attachments Ballot Results

jsonp/2.1/_index.md
=> Add ballot results for JSONP 2.1

xml-web-services/4.0/_index.md
Ballot results for successful ballot
=> Enshrine ballot results for XML Web Services 4.0

persistence/3.0/_index.md
See https://github.com/eclipse-ee4j/jpa-api/issues/368
=> Add Hibernate ORM 6.0.0.Final as compatible implementation

interceptors/2.1/_index.md
Add ballot result for the release review of Interceptor 2.1
=> add ballot result for interceptor 2.1

concurrency/3.0/_index.md
Add ballot results table and update the TCK download links
=> Ballot results for Concurrency 3.0

connectors/2.1/_index.md
And General Cleanup of the page
=> Add ballot results for Jakarta Connectors 2.1

tags/3.0/_index.md
Add ballot result for Tags 3.0
=> Add Tags 3.0 ballot result

pages/3.1/_index.md
Add ballot result for Jakarta Pages 3.1
=> Add Pages 3.1 ballot result

expression-language/5.0/_index.md
=> EL 5.0 Release Ballot Results

messaging/3.1/_index.md
=> Messaging 3.1 release ballot result

expression-language/5.0/_index.md
Kindly provided by Mark Thomas :)
=> Add EL 5.0 Release Summary

faces/_index.md, platform/10/_index.md, platform/8/_index.md, platform/9.1/_index.md, platform/9/_index.md
For https://github.com/jakartaee/jakarta.ee/issues/1478
=> Updated Meta Tags & SEO Optimizations for faces and platforms

mail/2.1/_index.md
Adds details about the Mail 2.1 release.
=> Add Mail 2.1 Release Details

security/3.0/_index.md
=> Fix Jakarta version typo and update date

xml-binding/3.0/jakarta-xml-binding-spec-3.0.html
<add URL here>
<add URL here>
<add URL here>
=> XML Binding - fix broken links in the 3.0 specification document

security/3.0/_index.md
=> Added ballot results for successful ballot - Security 3.0

restful-ws/3.1/_index.md
Links to SHA-256 and SIG files are corrected
=> Fix links in RESTful WS 3.1

bean-validation/3.0/_index.md, dependency-injection/2.0/_index.md
Update DI 2.0 Spec. page to add 2.0.2 TCK
=> Update Service Releases for BV and DI

dependency-injection/2.0/_index.md
=> Update DI with TCK 2.0.2 and API 2.0.1

faces/4.0/_index.md
=> Update for Faces 4.0.1 TCK

cdi/4.0/_index.md
=> Update TCK to 4.0.6

data/_index.md
[EMO Tracking Issue](https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/316)
=> Create Jakarta Data

coreprofile/10/_index.md
<add URL here>
<add URL here>
<add URL here>
N/A
=> Add ballot result for Jakarta EE 10 Core Profile

activation/2.1/_index.md
=> Apply new template to Activation

annotations/2.1/_index.md
=> Apply new template to Annotations

authorization/2.1/_index.md
=> Apply new template to Authorization

batch/2.1/_index.md
=> Apply new template to Batch

bean-validation/3.0/_index.md
=> Apply new template to Bean Validation

expression-language/5.0/_index.md
=> Apply new template to Expression Language

faces/4.0/_index.md
=> Apply new template to Faces

interceptors/2.1/_index.md
=> Apply new template for Interceptors

jsonp/2.1/_index.md
=> Apply new template for JSON Processing

messaging/3.1/_index.md
=> Apply new template to Messaging

security/3.0/_index.md
=> Apply new template to Security

pages/3.1/_index.md
=> Apply new template for Pages

tags/3.0/_index.md
=> Apply new template to Standard Tag Library

websocket/2.1/_index.md
=> Apply new template to WebSocket

xml-binding/4.0/_index.md
=> Apply new template for XML Binding

web-services-metadata/3.0/_index.md
=> Apply new template to Web Services Metadata

debugging/2.0/_index.md
=> Apply new template to DSOL

managedbeans/2.0/_index.md
=> Apply new template to Managed Beans

enterprise-ws/2.0/_index.md
=> Apply new template to Enterprise Web Services

enterprise-beans/4.0/_index.md
=> Apply new template to Enterprise Beans

dependency-injection/2.0/_index.md
=> Apply new template to Dependency Injection

cdi/4.0/_index.md
=> Apply new template to CDI

mvc/2.1/_index.md
=> Add ballot results for Jakarta MVC 2.1 Release Review

mvc/2.1/_index.md
Approved CCRs: 
- https://github.com/eclipse-ee4j/mvc-api/issues/91
- https://github.com/eclipse-ee4j/mvc-api/issues/92
=> Add compatible implementations of Jakarta MVC 2.1

restful-ws/4.0/_index.md
Signed-off-by: Santiago Pericasgeertsen <santiago.pericasgeertsen@oracle.com>
=> Updates for alignment with Jakarta 11 

persistence/3.1/_index.md
Signed-off-by: Scott Marlow <smarlow@redhat.com>
For issue https://github.com/jakartaee/specifications/issues/585
=> Update Jakarta Persistence TCK 3.1.1 for TCK challenge https://github.com/jakartaee/persistence/issues/388

config/0.1/_index.md, config/1.0/_index.md
=> Jakarta Config 1.0 Plan Review

coreprofile/10/_index.md, platform/10/_index.md, webprofile/10/_index.md
Update the text to use the word "specification". 
This also tightens up the association with the "Get Listed" link.
=> Be sure to include the word 'specification'

config/1.0/_index.md
See https://github.com/jakartaee/specifications/pull/580
Signed-off-by: Andrew Pielage <pandrex247@hotmail.com>
=> Config 1.0 Plan Review Ballot Results

config/_index.md
From: https://www.eclipse.org/lists/jakarta.ee-spec/msg02012.html
=> Add Config Creation Review Results

cdi/4.0/_index.md
=> Promote CDI TCK 4.0.9

persistence/3.2/_index.md
=> Persistence 3.2 plan

pages/4.0/_index.md
=> Pages 4.0 plan update

expression-language/6.0/_index.md
=> First draft of EL 6.0 plan

expression-language/6.0/_index.md
For https://github.com/jakartaee/specifications/pull/613
=> Expression Language 6.0 Plan Ballot Results

websocket/2.2/_index.md
=> WebSocket 2.2 plan update

faces/5.0/_index.md
<add URL here>
<add URL here>
<add URL here>
=> Faces 5.0 plan

interceptors/2.2/_index.md
<add URL here>
<add URL here>
<add URL here>
=> Plan for Jakarta Interceptors 2.2 release

authorization/3.0/_index.md
<add URL here>
<add URL here>
<add URL here>
=> Authorization 3.0 plan

data/1.0/_index.md
=> Plan for Jakarta Data 1.0

authorization/3.0/_index.md
<add URL here>
<add URL here>
<add URL here>
=> Add the ballot result for Authorization 3.0

interceptors/2.2/_index.md
<add URL here>
<add URL here>
<add URL here>
=> Add the ballot result for Interceptors 2.2 plan review

cdi/4.1/_index.md
<add URL here>
<add URL here>
<add URL here>
=> Plan for CDI 4.1 release

bean-validation/3.1/_index.md
=> Draft Jakarta Validation 3.1 release information

annotations/3.0/_index.md
=> Annotations 3.0 plan review

servlet/6.1/_index.md
=> Servlet 6.1 plan update

cdi/4.1/_index.md
<add URL here>
<add URL here>
<add URL here>
=> Add the ballot result for CDI 4.1 plan review

security/4.0/_index.md
<add URL here>
<add URL here>
<add URL here>
=> Security 4.0 plan

cdi/4.0/_index.md
<add URL here>
<add URL here>
<add URL here>
=> Promote CDI TCK 4.0.11

platform/11/_index.md
=> Jakarta EE Platform 11

coreprofile/11/_index.md
=> Jakarta EE Core Profile 11

webprofile/11/_index.md
=> Jakarta EE  Web Profile 11

webprofile/11/_index.md
<add URL here>
<add URL here>
<add URL here>
=> Add the ballot result for Jakarta EE 11 Web Profile Plan Review

coreprofile/10/_index.md
Please promote staged TCK http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl//jakarta-core-profile-tck-10.0.3.zip to address accepted TCK challenge https://github.com/jakartaee/platform-tck/issues/1196
Thank you!
=> Promote Core Profile TCK 10.0.3 to address accepted TCK challenge https://github.com/jakartaee/platform-tck/issues/1196

platform/11/_index.md
modified:   platform/11/_index.md
=> On branch master Verify rendering pipeline works for me.

faces/4.0/_index.md
Please also promote the binary from 
https://www.eclipse.org/downloads/download.php?file=/faces/jakartaee10/staged/eftl/jakarta-faces-tck-4.0.3.zip
to
https://download.eclipse.org/jakartaee/faces/4.0/jakarta-faces-tck-4.0.3.zip
=> Promote Faces TCK 4.0.3

restful-ws/_index.md
Adds the `latest_updates_video` front matter param for RESTful Web Services.
=> Add latest updates video for restful-ws

batch/2.1/_index.md, batch/2.1/changelog.md
Please publish EFTL bundle:
https://download.eclipse.org/jakartabatch/tck/eftl/jakarta.batch.official.tck-2.1.5.zip
The contents of the change are described in the change log in this PR.   
Also some summary context on the mailing list:
- https://www.eclipse.org/lists/jakartabatch-dev/msg00320.html
- https://www.eclipse.org/lists/jakartabatch-dev/msg00321.html
@Emily-Jiang (thought I'd notify someone since this was sitting as a draft for awhile..thanks).
=> Release Jakarta Batch TCK 2.1.5

authorization/3.0/_index.md
=> Add the ballot results for authorization 3.0

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Added the Mentor Spec Review Checklist
=> Add the spec mentor review checklist to the Spec Review PR template

bean-validation/3.1/_index.md
Updated the latest BV 3.1 TCK version to 3.1.1
=> - Update latest Validation TCK to 3.1.1

concurrency/3.1/_index.md
Ballot results for Concurrency 3.1 release review
=> Add ballot results for successful Concurrency 3.1 release review

data/1.0/_index.md
Add ballot result for Jakarta Data 1.0
=> add the ballot result for Jakarta Data 1.0

pages/4.0/_index.md
Add the ballot result for Jakarta Pages 4.0.0
=> Add the ballot result for Jakarta Pages 4.0

data/1.0/_index.md
=> Jakarta data 1.0 typo

pages/_index.md
Resolves https://github.com/jakartaee/jakarta.ee/issues/1875
=> Update metatags for Jakarta Pages

authentication/3.1/_index.md
=> Add Ballot Results for Jakarta Authentication 3.1

concurrency/3.1/_index.md
@edbratt can publish the updated TCK distribution that has been promoted here: https://download.eclipse.org/ee4j/cu/jakartaee11/promoted/eftl/?  I'll keep this PR in draft until that is done.
=> Jakarta Concurrency 3.1 service release

tags/3.0/_index.md
Please promote https://download.eclipse.org/jakartaee/tags/3.0/jakarta-tags-tck-3.0.1.zip for TCK challenges:
- https://github.com/jakartaee/tags/issues/255
- https://github.com/jakartaee/tags/issues/256
- https://github.com/jakartaee/platform-tck/issues/1313
=> Please promote Tags TCK https://download.eclipse.org/jakartaee/tags/3.0/jakarta-tags-tck-3.0.1.zip

security/3.0/_index.md
Following the challenge as descibed here: https://github.com/jakartaee/security/issues/297
@ivargrimstad can you promote https://www.eclipse.org/downloads/download.php?file=/security/jakartaee10/staged/eftl/jakarta-security-tck-3.0.2.zip&r=1 
to https://download.eclipse.org/jakartaee/security/3.0/jakarta-security-tck-3.0.2.zip?
=> Promote Jakarta Security TCK 3.0.2

platform/9.1/_index.md
https://www.eclipse.org/downloads/download.php?file=/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-jakartaeetck-9.1.1.zip
TCK challenge addressed in the Platform TCK service release:
https://github.com/jakartaee/platform-tck/issues/1313
=> promote Platform TCK jakarta-jakartaeetck-9.1.1.zip

security/_index.md
Currently - live on page - _could not load project_ badge:
=> Fix project_id for Security

coreprofile/10/_index.md
=> Fix Jakarta EE 10 Core Profile API jar link

data/1.0/_index.md
Fixes https://github.com/jakartaee/data/issues/942
=> Add JNoSQL to Jakarta Data compatible implementations

cdi/5.0/_index.md
=> Jakarta CDI 5.0 (under development)

cdi/5.0/_index.md, data/1.1/_index.md
Add the plan review ballot results for CDI 5.0 and Data 1.1
=> Add plan review ballot results for Data 1.1 and CDI 5.0

query/1.0/_index.md, query/_index.md
Creates the Jakarta Query project at:
https://jakarta.ee/specifications/query/
See the proposal here: https://projects.eclipse.org/proposals/jakarta-query
=> Create Jakarta Query

pages/4.1/_index.md
=> Jakarta Pages 4.1 Plan Review

websocket/2.3/_index.md
=> Jakarta WebSocket 2.3.0 Plan Review

expression-language/6.1/_index.md
=> Jakarta Expression Language 6.1.0 Plan Review

expression-language/6.1/_index.md
Adds the ballot results for the titular plan review.
Plan review PR: https://github.com/jakartaee/specifications/pull/805
=> Add Expression Language 6.1 Plan Review Ballot Results

faces/5.0/_index.md
=> Jakarta Faces 5.0 Plan Review

concurrency/3.2/_index.md
=> Jakarta Concurrency 3.2 Plan Review

jsonb/3.1/_index.md
=> JSON Binding 3.1 Plan Review

transactions/2.1/_index.md
<add URL here>
<add URL here>
<add URL here>
=> Initial plan for Jakarta Transactions 2.1

persistence/4.0/_index.md
This draft plan has not yet been reviewed by @lukasj.
=> Release plan for Persistence 4.0

batch/2.2/_index.md
=> Jakarta Batch 2.2 Plan Review

mvc/3.1/_index.md
Adds the titular ballot results
=> Jakarta MVC 3.1 Plan Review Ballot Results

annotations/3.1/_index.md
=> Jakarta Annotations 3.1 Plan Review

bean-validation/4.0/_index.md
=> Jakarta Validation 4.0 plan review information

security/5.0/_index.md
=> Security 5.0 plan

faces-bridge/7.0/_index.md, faces-bridge/_index.md
https://jakarta.ee/specifications/faces-bridge/
Jakarta Faces Bridge Proposal:
https://projects.eclipse.org/proposals/jakarta-faces-bridge
=> Creates the Jakarta Portlet Bridge project (renamed from Jakarta Faces Bridge)

portlet/4.0/_index.md, portlet/_index.md
https://jakarta.ee/specifications/portlet/
Jakarta Portlet Project Proposal:
https://projects.eclipse.org/proposals/jakarta-portlet
=> Creates the Jakarta Portlet project:

webprofile/12/_index.md
=> Jakarta EE Web Profile 12 release plan

mail/2.2/_index.md
=> Jakarta Mail 2.2 Plan Review

jsonp/2.2/_index.md
=> Jakarta JSON Processing 2.2 Plan Review

jsonp/2.2/_index.md, tags/3.1/_index.md
add ballot results for json-p 2.2 and tags 3.1
=> Add ballot results for json-p 2.2 and tags 3.1

coreprofile/12/_index.md
Add the ballot results for the plan review of Jakarta EE 12 Core Porfile
=> Add the plan review ballot for Jakarta EE 12 Core Profile

activation/2.2/_index.md
=> Jakarta Activation 2.2 Plan Review

mvc/3.0/_index.md
Also updates the date - I'm not sure it should still be the date of the plan
=> MVC 3.0 Release Ballot Results

data/_index.md, persistence/_index.md
Adds video guides to Data and Persistence
=> Add video guides

servlet/6.1/_index.md
Respin of https://github.com/jakartaee/specifications/pull/856
https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/nio/charset/Charset.html
Presumably implemented by https://github.com/jakartaee/servlet/pull/491
Fixes https://github.com/jakartaee/specifications/issues/857
=> Fix typo in _index.md
