jakartaee/specifications

- transactions/1.3/_index.md
More inconsistencies with Transactions _index.md.  The pdf and html file names were incorrect.  And, the text link for the maven coordinates had the wrong version.
> pdf, html, and maven links were incorrect

- annotations/1.3/_index.md
- authentication/1.1/_index.md
- authorization/1.5/_index.md
- batch/1.0/_index.md
- bean-validation/2.0/_index.md
- cdi/2.0/_index.md
- concurrency/1.1/_index.md
- connectors/1.7/_index.md
- debugging/1.0/_index.md
- dependency-injection/1.0/_index.md
- expression-language/3.0/_index.md
- faces/2.3/_index.md
- interceptors/1.2/_index.md
- jsonb/1.0/_index.md
- jsonp/1.1/_index.md
- mail/1.6/_index.md
- managedbeans/1.0/_index.md
- messaging/2.0/_index.md
- pages/2.3/_index.md
- persistence/2.2/_index.md
- platform/8/_index.md
- restful-ws/2.1/_index.md
- security/1.0/_index.md
- servlet/4.0/_index.md
- tags/1.2/_index.md
- transactions/1.3/_index.md
- webprofile/8/_index.md
- websocket/1.1/_index.md
- xml-registries/1.0/_index.md
- xml-rpc/1.1/_index.md
- TCK urls have been updated to favor the 'jakarta-' version of files if the 'eclipse-' prefix was used.
- All downloads.eclipse.org URLs now use `https`
- After each TCK link there is a new `(sig,sha,pub)` set of links for verification
> Update TCK urls to jakarta branded files. Add "(sig, sha, pub)" links.

- activation/2.0/_index.md
- enterprise-beans/4.0/_index.md
- restful-ws/3.0/_index.md
JAX-RS has decided to go with a simple release for Jakarta EE 9, thus they are now covered by the overall Jakarta EE 9 Release Plan.
I have also updated the templates for EJB and JAF to better represent the need for a separate plan and review.
> update jaxrs, ejb, and jaf templates

- enterprise-beans/4.0/_index.md
(all text revised as of Tue Feb  4)
The current state of this PR is still solidly 'draft' as we have a few things to discuss.
First, see this page for a draft of the proposed text for the detailed plan.  This is in PR form:
- https://github.com/eclipse-ee4j/ejb-api/blob/053b5ceb50b5b3c63dd99f0adf568038045f0a83/4.0-PLAN.adoc#jakarta-enterprise-beans-40
- https://github.com/eclipse-ee4j/ejb-api/pull/64
Open discussion item on if this is an acceptable place for a plan to live.  There is an open bug requesting a Github Pages setup:
- https://bugs.eclipse.org/bugs/show_bug.cgi?id=559668
Second, I still feel we need executive summaries on our specification pages.  Understood we do not want detailed plans there, however there needs to be a one or two paragraph max executive-level overview so …
> Enterprise Beans 4.0 Plan Review

- pull_request_template.md
Main point was to indicate that separating the javadoc into its own PR is an optional exercise.  As I was updating that, I found a couple of minor formatting items that I also cleaned up.
> Updated PR template to clarify that the second PR for the javadoc is optional

- activation/1.2/_index.md
Fix to download link to Jakarta Activation 1.2 TCK and SHA file links. (FWIW SHA appears to match that in the CCR from last year.)
Signed-off-by: Ed Bratt <ed.bratt@oracle.com>
> Corrected download links to TCK for Jakarta Activation 1.2

- bean-validation/3.0/_index.md
Updated _index.md with the ballot results.  And, corrected the sha link for the TCK.
> Insert Bean Validation ballot and correct sha link

- dependency-injection/2.0/_index.md
using the https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/ job.
This list goes on the committed spec index page.
Signed-off-by: Ed Bratt <ed.bratt@oracle.com>
> Updated ballot results and confirmed TCK download specifics

- activation/1.2/_index.md
This fixes broken link to Eclipse implementation of Jakarta Activation 1.2.2 CI at https://jakarta.ee/specifications/activation/1.2/
> Fix broken link for JAF impl

- transactions/2.0/_index.md
Please see https://github.com/eclipse-ee4j/jta-api/issues/183#issuecomment-725408793
> Updated link to an archived version of Glassfish for Transactions 2.0 as the current link returns 404

- jsonp/2.0/_index.md
The link to Maven central is actually good.
> Fix JSONP maven coordinates label

- platform/9/_index.md
- restful-ws/3.0/_index.md
- webprofile/9/_index.md
Signed-off-by: Scott Marlow <smarlow@redhat.com>
Tracking specifications issue https://github.com/jakartaee/specifications/issues/328
https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-restful-ws-tck-3.0.1.zip
Tracking specifications issue https://github.com/jakartaee/specifications/issues/328
https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-jakartaeetck-9.0.2.zip
> Update Platform TCK 9.0.2 + Jakarta RESTful Web Services 3.0.1 for TCK challenge 

- platform/9.1/_index.md
- webprofile/9.1/_index.md
Initial content and format for the Jakarta EE 9.1 release.  Most of the template PR checklist does not apply at this stage.  As the 9.1 release progresses, more data will be added to these pages...
More information will be coming shortly...
https://projects.eclipse.org/projects/ee4j.jakartaee-platform/releases/9.1
https://projects.eclipse.org/projects/ee4j.jakartaee-platform/releases/web-profile-9.1
> Prime Platform and Web Profile Spec pages for 9.1 release

- service_release_pr_template.md
Updating the Service Release template per the discussions with Lukas on JAF and Mail.  I think I caught everything, but take a look.  If we get this good, then we can move onto the other templates.
Also, is there a way to select which PR template to use when creating a PR (similar to selecting a template when creating an Issue)?  We should do that.
> Update Service Release template per experiments with JAF and Mail

- platform/8/_index.md
- platform/9.1/_index.md
- platform/9/_index.md
- webprofile/8/_index.md
- webprofile/9.1/_index.md
- webprofile/9/_index.md
Per the Spec Committee call today and the recent decision to list the CI used for Ratification in the top matter of the page, I have updated the _index.md files for Jakarta EE 8, 9, and 9.1.  Besides the CI Ratification message, we also decided to just reference the official Compatible Products page for the Platform and Web Profile.
> Update Compatible Impl references

- restful-ws/3.1/_index.md
Signed-off-by: Santiago Pericasgeertsen <santiago.pericasgeertsen@oracle.com>
https://projects.eclipse.org/projects/ee4j.jaxrs/releases/3.1.0
> Jakarta RESTful Web Services 3.1 Plan Review

- batch/2.1/_index.md
Signed-off-by: Scott Kurz <skurz@us.ibm.com>
https://projects.eclipse.org/projects/ee4j.batch/releases/2.1.0
> Jakarta Batch 2.1 Plan Review

- pages/3.1/_index.md
> Jakarta JSP 3.1 Plan Review

- platform/9.1/_index.md
- webprofile/9.1/_index.md
Looks like the new tab for the 9.1 Compatible Implementations page used an underscore (_) instead of a period (.)...
> fix the links for the 9.1 Compatible Implementations page

- xml-binding/2.3/_index.md
- xml-binding/4.0/_index.md
https://projects.eclipse.org/projects/ee4j.jaxb/releases/4.0
> Jakarta XML Binding 4.0 Plan Review

- activation/2.0/_index.md
- mail/2.0/_index.md
- xml-binding/3.0/_index.md
Add JDK 11 compatible TCK links for Activation (2.0.1), Mail (2.0.1), and XML Binding (3.0.1)
These TCKs are already promoted to the Spec. download. For details, see each of: [Activation](https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/145/), [Mail](https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/146/), [XML Binding](https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/147/)
Signed-off-by: Ed Bratt <ed.bratt@oracle.com>
> JDK 11 TCK links 

- servlet/6.0/_index.md
_index.md file had broken links to javadocs, PDF and HTML versions of the spec
> Corrected broken links on _index.md

- batch/2.1/_index.md
- batch/2.1/changelog.md
This PR has two aspects:
The Jakarta Batch 2.1 spec page: https://jakarta.ee/specifications/batch/2.1/ will be updated to point to the latest API JAR Maven coordinates.
This is of no real value from a specification point of view.   It is just motivated by a general desire to keep things up to date.  We link to specific Maven API JAR coordinates, might as well use the latest.
Though I'm not sure this is externally visible, those working within this **specifications** repository will be able to read the history of the 2.1.1 API Maven release vs. the 2.1.1 TCK Maven release.   It seems this might be helpful to someone.  
Note there is NOT going to be an Eclipse ee4j.batch 2.1.1 release (at https://projects.eclipse.org/projects/ee4j.batch/releases)
> Update for Jakarta Batch 2.1.1 (API JAR, Maven-only) release 

- authentication/3.0/_index.md
Before merging this, TCK should be promoted to Eclipse download location 
from https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/promoted/eftl/jakarta-authentication-tck-3.0.1.zip 
to https://download.eclipse.org/jakartaee/authentication/3.0/jakarta-authentication-tck-3.0.1.zip
cc @ivargrimstad 
> Add authentication service release 3.0.1 and update GF to M7

- restful-ws/3.1/_index.md
As discussed; adding release 3.1.1 of the REST TCK.
Should only be merged after copying from:
https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-restful-ws-tck-3.1.1.zip
to
https://download.eclipse.org/jakartaee/restful-ws/3.1/jakarta-restful-ws-tck-3.1.1.zip
> Add REST TCK 3.1.1 Service release info

- concurrency/3.0/_index.md
https://download.eclipse.org/ee4j/cu/jakartaee10/staged/eftl/concurrency-tck-3.0.2.zip 
needs to be promoted to
https://download.eclipse.org/jakartaee/concurrency/3.0/concurrency-tck-3.0.2.zip
> Add service release of concurrency TCK to spec page

- concurrency/3.0/_index.md
- soap-attachments/3.0/_index.md
Update for Concurrency 3.0 and SOAP 3.0 pages to add headings as proposed in new [Spec. committee template](https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md).
> Apply revised templates for Concurrency 3.0 and SOAP 3.0

- authentication/3.0/_index.md
> Apply new template to Authentication

- coreprofile/10/_index.md
The URLs to the zip and signature files are incorrect - this (hopefully) fixes them.
> Fix CoreProfile TCK Links

- coreprofile/10/_index.md
- platform/10/_index.md
- webprofile/10/_index.md
See #595 for background.
This pull request adds the Jakarta EE Compatible logo to the platform and two profiles.
At least for now, this is experiment to see whether or not it gets rendered correctly. 
Please don't merge until I get a chance to run this past the specification committee.
> Add the Jakarta EE Compatible logo

- faces/4.0/_index.md
Please run the TCK release script to make the release official and transfer 
from
https://www.eclipse.org/downloads/download.php?file=/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-faces-tck-4.0.2.zip
to
https://download.eclipse.org/jakartaee/faces/4.0/jakarta-faces-tck-4.0.2.zip
cc @ivargrimstad @Emily-Jiang
> Add TCK 4.0.2 as a third TCK, and update Mojarra to 4.0.2

- security/3.0/_index.md
Please run the TCK release script to make the release official and transfer 
from
https://www.eclipse.org/downloads/download.php?file=/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-security-tck-3.0.1.zip
to
https://download.eclipse.org/jakartaee/security/3.0/jakarta-security-tck-3.0.1.zip
cc @ivargrimstad @Emily-Jiang
> Add TCK 3.0.1 as a second TCK, and update Soteria to 3.0.2

- activation/2.1/_index.md
promote jakarta activation 2.1.1 tck addressing [linked tck challenge](https://github.com/jakartaee/jaf-api/issues/98), please.
Staged TCK binary: https://www.eclipse.org/downloads/download.php?file=/ee4j/jaf/jakartaee10/staged/eftl/jakarta-activation-tck-2.1.1.zip
> activation TCK 2.1.1

- cdi/4.0/_index.md
CDI TCK 4.0.10 was released on May 29 and is available in Central but I forgot to update it here.
CC @scottmarlow - follow up on your thread from the mailing list, sorry I left out this step :)
> Promote CDI TCK 4.0.10

- concurrency/3.1/_index.md
> Concurrency 3.1 plan

- cdi/4.0/_index.md
A new version of CDI TCK was released today and addressed two accepted TCK challenges:
* https://github.com/jakartaee/cdi-tck/issues/487
* https://github.com/jakartaee/cdi-tck/issues/485
> Promote CDI TCK 4.0.12

- xml-binding/4.0/_index.md
Please promote the XML Binding 4.0.1 TCK for accepted challenge https://github.com/jakartaee/jaxb-tck/issues/82
Could one of the Specifications Committee members please run the https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release job to promote the https://www.eclipse.org/downloads/download.php?file=/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-xml-binding-tck-4.0.1.zip TCK
I think the parameters to pass in would be ([as per previous job](https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/211/parameters/)):
1. SPEC_NAME=xml-binding
2. SPEC_VERSION=4.0
3. FILE_URLS=https://www.eclipse.org/downloads/download.php?file=/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-xml-binding-tck-4.0.1.zip
> Promote XML Binding 4.0.1 TCK for challenge issue 82

- coreprofile/10/apidocs/search.js
- platform/10/apidocs/search.js
- webprofile/10/apidocs/search.js
Platform and profile Javadocs for EE 10 don't use modules, but the generated Javadoc wants to add module into the URL, which results in "/undefined/" in the URL. 
This fix avoids adding "undefined" into the URL and fixes https://github.com/jakartaee/platform/issues/613.
---
A preview in Netlify here: https://deploy-preview-676--jakartaee-specifications.netlify.app/specifications/platform/10/apidocs/
---
Note: The trailing slash is important for URLs to JS resources to work. The trailing slash is not added by Netlify into the generated pages, so if you browse to the Javadocs from the root Netlify preview page, the Javadoc page will be broken. This doesn't happen in the jakarta.ee page, because probably the server contains a redirect from /apidocs to /apidocs/.
> Fix Searching in the EE10 Javadoc leads to a broken link

- cdi/4.0/_index.md
Today I've issued a maintenance release for CDI TCK (4.0.13) that contains fixes for two challenges:
* https://github.com/jakartaee/cdi-tck/pull/503
* https://github.com/jakartaee/cdi-tck/pull/515
> Promote CDI TCK 4.0.13

- coreprofile/11/_index.md
- platform/11/_index.md
- webprofile/11/_index.md
modified:   coreprofile/11/_index.md
modified:   platform/11/_index.md
modified:   webprofile/11/_index.md
This change allows for several things while not restricting anything.
- It *allows* compatible runtimes to certify on Java SE 17 **OR** 21, while simultaneously *allowing* Concurrency to provide Java SE version runtime aware support for Virtual Threads.
- It *allows* users who are not at liberty to run Java SE 21 to adopt Jakarta EE 11.
- It *allows* us to keep our delivery schedule of June/July 2024 to complete Jakarta EE 11.
> On branch edburns-msft-jea-276-progress-review: Commence progress review

- annotations/2.1/_index.md
Annotation spec in v 2.1 in the end added _@Nonnull_ instead of _@NotNull_ as is said on the spec page. Would be good to fix the name here to avoid confusion. See https://github.com/jakartaee/common-annotations-api/issues/109
> ca#109: spec page should list @Nonnull instead of @NotNull

- restful-ws/4.0/_index.md
The purpose of this PR is to update the existing Jakarta RESTful Web Services-4.0 plan with the minimal content discussed on the Jakarta Platform call.
> Update Jakarta Rest-4.0 content

- expression-language/6.0/_index.md
Adds the Expression Language 6.0 release ballot results.
Original PR: https://github.com/jakartaee/specifications/pull/701
> Expression Language 6.0 Release Ballot Results

- servlet/6.1/_index.md
Currently at https://jakarta.ee/specifications/servlet/6.1/:
> Fix text of Javadoc anchor that is for Servlet 6.1

- restful-ws/4.0/_index.md
Adding release 4.0.1 of the Jakarta RESTful Web Services TCK
Should only be merged after copying from:
[https://www.eclipse.org/downloads/download.php?file=/ee4j/restful-ws/tck/eftl/jakarta-restful-ws-tck-4.0.1.zip](https://www.eclipse.org/downloads/download.php?file=/ee4j/restful-ws/tck/eftl/jakarta-restful-ws-tck-4.0.1.zip)
to
https://download.eclipse.org/jakartaee/restful-ws/4.0.1/jakarta-restful-ws-tck-4.0.1.zip
> Add REST TCK 4.0.1 Service release info

- faces/4.1/_index.md
[Faces 4.0](https://jakarta.ee/specifications/faces/4.0/) has it:
[Faces 4.1](https://jakarta.ee/specifications/faces/4.1/) does not have it:
4.1.0 was referenced in:
- https://github.com/jakartaee/specifications/pull/738
> Include maven coordinates for Faces 4.1 API

- restful-ws/3.0/_index.md
- restful-ws/3.1/_index.md
- restful-ws/4.0/_index.md
The links seems fine, but the texts do not correspond to them.
> Fix text for maven coordinates in restful-ws 3.0/3.1/4.0

- data/1.0/_index.md
Currently text 
doesn't follow GAV-like format.
> Fix GAV for Data

- messaging/_index.md
Currently - live on page - _could not load project_ badge:
> Fix project_id for Messaging

- servlet/6.1/_index.md
servlet/6.1/_index.md
jakarta-servlet-spec-6.1.pdf
jakarta-servlet-spec-6.1.html
https://github.com/jakartaee/specifications/blob/master/servlet/6.1/_index.md
Tested the staged Servlet 6.1.1 TCK version.
N/A
https://www.eclipse.org/downloads/download.php?file=/ee4j/servlet/jakartaee11/staged/eftl/jakarta-servlet-tck-6.1.1.zip
N/A
N/A
> Promote Servlet 6.1.1 TCK

- authentication/3.1/_index.md
https://download.eclipse.org/security/jakartaee11/staged/eftl/jakarta-authentication-tck-3.1.1.zip
needs to be promoted to
https://download.eclipse.org/jakartaee/authentication/3.1/jakarta-authentication-tck-3.1.1.zip
cc @ivargrimstad @jhanders34
> Add 3.1.1. service release of authentication TCK to spec page

- coreprofile/10/_index.md
https://github.com/jakartaee/platform-tck/issues/1960
The staged TCK binary is at: 
https://www.eclipse.org/downloads/download.php?file=/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-core-profile-tck-10.0.4.zip
> Update Core Profile 10 TCK service release version to 10.0.4

- faces/4.1/_index.md
The link is found here: https://jakarta.ee/specifications/faces/4.1/
Spec issues: 
- https://github.com/jakartaee/faces/issues/1707
- https://github.com/jakartaee/faces/issues/1549
The original plan was to remove them, but we couldn't do that in a minor release without deprecation first. So, the new approach was to deprecate them in 4.1 and remove in 5.0 (which we have spec approval for).
> Update Faces 4.1 Documentation

- restful-ws/5.0/_index.md
> Jakarta RESTful Web Services 5.0 Plan Review

- nosql/1.1/_index.md
> Plan for Jakarta NoSQL 1.1

- portlet-bridge/_index.md
> Fix project_id of Portlet Bridge

- tags/3.1/_index.md
> Jakarta Standard Tag Library 3.1.0 plan review

- bean-validation/3.1/_index.md
- cdi/4.1/_index.md
- cdi/5.0/_index.md
- concurrency/1.1/_index.md
- connectors/1.7/_index.md
- connectors/2.0/_index.md
- data/1.0/_index.md
- faces/4.1/_index.md
- interceptors/2.2/_index.md
- pages/4.1/_index.md
- platform/9/_index.md
- platform/9/_index.zh.md
- tags/3.1/_index.md
- webprofile/9/_index.md
- websocket/2.2/_index.md
- websocket/2.3/_index.md
- Update date for pages, tags and websocket vNext release to not be in the future so that it displays now and not a year from now
- Remove references to download.php since it will be removed at the end of the year.  Switch to the non php url.
- Clean up some additional Release Review TBD entries in a few pages
> Fix up some page references
